import './globals.scss';
import Link from 'next/link';
import { CookieBanner } from './CookieBanner';
import style from './layout.module.scss';

export const metadata = {
  title: { default: 'Next Example | UpLeveled', template: '%s | UpLeveled' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CookieBanner />
        <nav className={style.navigator}>
          <Link href="/">home</Link> <Link href="/animals">animals</Link>{' '}
          <Link href="/fruits">fruits</Link>
          {Math.floor(Math.random() * 10)}
        </nav>
        {children}
      </body>
    </html>
  );
}
