import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Next Example | UpLeveled', template: '%s | UpLeveled' },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">home</Link> <Link href="/animals">animals</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
